name: build image
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '05 10 * * *'  # 10:05am UTC everyday
  workflow_dispatch:

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_NAME: hostdeck

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  push-ghcr:
    name: Build and push image
    runs-on: ubuntu-24.04
    continue-on-error: false
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Define env.SHA_HEAD_SHORT
        run: |
          echo "SHA_HEAD_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV

      # Checkout push-to-registry action GitHub repository
      - name: Checkout Push to Registry action
        uses: actions/checkout@v4

      - name: Check just syntax
        uses: ublue-os/just-action@v1

      - name: Maximize build space
        uses: ublue-os/remove-unwanted-software@v7

      # Build image using buildah and save it to raw-img
      - name: Build Image
        id: build_image
        run: |
          sudo buildah build \
            --target hostdeck \
            --build-arg IMAGE_NAME=${{ env.IMAGE_NAME }} \
            --build-arg IMAGE_FLAVOR=main \
            --build-arg IMAGE_VENDOR=${{ env.IMAGE_REGISTRY }} \
            --build-arg BASE_IMAGE_NAME=kinoite \
            --build-arg BASE_IMAGE_FLAVOR=main \
            --build-arg FEDORA_VERSION=40 \
            --build-arg KERNEL_FLAVOR=fsync \
            --build-arg SHA_HEAD_SHORT=${{ env.SHA_HEAD_SHORT }} \
            --tag raw-img .
